# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\python\serial\serial.ui'
#
# Created: Thu Oct 30 22:32:46 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(586, 386)
        Dialog.setSizeGripEnabled(True)
        self.horizontalLayout_4 = QtGui.QHBoxLayout(Dialog)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.author = QtGui.QLabel(Dialog)
        self.author.setObjectName(_fromUtf8("author"))
        self.verticalLayout_7.addWidget(self.author)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.PortLable = QtGui.QLabel(Dialog)
        self.PortLable.setObjectName(_fromUtf8("PortLable"))
        self.verticalLayout.addWidget(self.PortLable)
        self.baundlabel = QtGui.QLabel(Dialog)
        self.baundlabel.setObjectName(_fromUtf8("baundlabel"))
        self.verticalLayout.addWidget(self.baundlabel)
        self.bytesizelabel = QtGui.QLabel(Dialog)
        self.bytesizelabel.setObjectName(_fromUtf8("bytesizelabel"))
        self.verticalLayout.addWidget(self.bytesizelabel)
        self.stopbitslabel = QtGui.QLabel(Dialog)
        self.stopbitslabel.setObjectName(_fromUtf8("stopbitslabel"))
        self.verticalLayout.addWidget(self.stopbitslabel)
        self.paritylabel = QtGui.QLabel(Dialog)
        self.paritylabel.setObjectName(_fromUtf8("paritylabel"))
        self.verticalLayout.addWidget(self.paritylabel)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.port = QtGui.QComboBox(Dialog)
        self.port.setObjectName(_fromUtf8("port"))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.port.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.port)
        self.baund = QtGui.QComboBox(Dialog)
        self.baund.setObjectName(_fromUtf8("baund"))
        self.baund.addItem(_fromUtf8(""))
        self.baund.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.baund)
        self.bytesize = QtGui.QComboBox(Dialog)
        self.bytesize.setObjectName(_fromUtf8("bytesize"))
        self.bytesize.addItem(_fromUtf8(""))
        self.bytesize.addItem(_fromUtf8(""))
        self.bytesize.addItem(_fromUtf8(""))
        self.bytesize.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.bytesize)
        self.stopbits = QtGui.QComboBox(Dialog)
        self.stopbits.setObjectName(_fromUtf8("stopbits"))
        self.stopbits.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.stopbits)
        self.parity = QtGui.QComboBox(Dialog)
        self.parity.setObjectName(_fromUtf8("parity"))
        self.parity.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.parity)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.verticalLayout_8.addLayout(self.verticalLayout_7)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.verticalLayout_8.addWidget(self.line_2)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.openPortButton = QtGui.QPushButton(Dialog)
        self.openPortButton.setObjectName(_fromUtf8("openPortButton"))
        self.verticalLayout_3.addWidget(self.openPortButton)
        self.SendDataButton = QtGui.QPushButton(Dialog)
        self.SendDataButton.setObjectName(_fromUtf8("SendDataButton"))
        self.verticalLayout_3.addWidget(self.SendDataButton)
        self.ClearSendButton = QtGui.QPushButton(Dialog)
        self.ClearSendButton.setObjectName(_fromUtf8("ClearSendButton"))
        self.verticalLayout_3.addWidget(self.ClearSendButton)
        self.ClearReceiveButton = QtGui.QPushButton(Dialog)
        self.ClearReceiveButton.setObjectName(_fromUtf8("ClearReceiveButton"))
        self.verticalLayout_3.addWidget(self.ClearReceiveButton)
        self.recountButton = QtGui.QPushButton(Dialog)
        self.recountButton.setObjectName(_fromUtf8("recountButton"))
        self.verticalLayout_3.addWidget(self.recountButton)
        self.verticalLayout_8.addLayout(self.verticalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout_8)
        spacerItem = QtGui.QSpacerItem(20, 365, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.horizontalLayout_4.addItem(spacerItem)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_4.addWidget(self.line)
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.receiveeditlabel = QtGui.QLabel(Dialog)
        self.receiveeditlabel.setObjectName(_fromUtf8("receiveeditlabel"))
        self.horizontalLayout_2.addWidget(self.receiveeditlabel)
        self.receivecount = QtGui.QLCDNumber(Dialog)
        self.receivecount.setDigitCount(25)
        self.receivecount.setObjectName(_fromUtf8("receivecount"))
        self.horizontalLayout_2.addWidget(self.receivecount)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.ReceivetextBrowser = QtGui.QTextBrowser(Dialog)
        self.ReceivetextBrowser.setObjectName(_fromUtf8("ReceivetextBrowser"))
        self.verticalLayout_4.addWidget(self.ReceivetextBrowser)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.sendeditlabel = QtGui.QLabel(Dialog)
        self.sendeditlabel.setObjectName(_fromUtf8("sendeditlabel"))
        self.horizontalLayout_3.addWidget(self.sendeditlabel)
        self.sendcount = QtGui.QLCDNumber(Dialog)
        self.sendcount.setDigitCount(25)
        self.sendcount.setObjectName(_fromUtf8("sendcount"))
        self.horizontalLayout_3.addWidget(self.sendcount)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.SendtextEdit = QtGui.QTextEdit(Dialog)
        self.SendtextEdit.setObjectName(_fromUtf8("SendtextEdit"))
        self.verticalLayout_5.addWidget(self.SendtextEdit)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_6)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "Dialog", None))
        self.author.setText(_translate("Dialog", "Made By Ginger", None))
        self.PortLable.setText(_translate("Dialog", "端口", None))
        self.baundlabel.setText(_translate("Dialog", "波特率", None))
        self.bytesizelabel.setText(_translate("Dialog", "数据位", None))
        self.stopbitslabel.setText(_translate("Dialog", "停止位", None))
        self.paritylabel.setText(_translate("Dialog", "校验", None))
        self.port.setItemText(0, _translate("Dialog", "COM1", None))
        self.port.setItemText(1, _translate("Dialog", "COM2", None))
        self.port.setItemText(2, _translate("Dialog", "COM3", None))
        self.port.setItemText(3, _translate("Dialog", "COM4", None))
        self.port.setItemText(4, _translate("Dialog", "COM5", None))
        self.port.setItemText(5, _translate("Dialog", "COM6", None))
        self.port.setItemText(6, _translate("Dialog", "COM7", None))
        self.port.setItemText(7, _translate("Dialog", "COM8", None))
        self.port.setItemText(8, _translate("Dialog", "COM9", None))
        self.port.setItemText(9, _translate("Dialog", "COM10", None))
        self.baund.setItemText(0, _translate("Dialog", "9600", None))
        self.baund.setItemText(1, _translate("Dialog", "115200", None))
        self.bytesize.setItemText(0, _translate("Dialog", "8", None))
        self.bytesize.setItemText(1, _translate("Dialog", "7", None))
        self.bytesize.setItemText(2, _translate("Dialog", "6", None))
        self.bytesize.setItemText(3, _translate("Dialog", "5", None))
        self.stopbits.setItemText(0, _translate("Dialog", "1", None))
        self.parity.setItemText(0, _translate("Dialog", "no", None))
        self.openPortButton.setText(_translate("Dialog", "打开串口", None))
        self.SendDataButton.setText(_translate("Dialog", "发送数据", None))
        self.ClearSendButton.setText(_translate("Dialog", "清空发送", None))
        self.ClearReceiveButton.setText(_translate("Dialog", "清空接收", None))
        self.recountButton.setText(_translate("Dialog", "重新计数", None))
        self.receiveeditlabel.setText(_translate("Dialog", "接收区", None))
        self.sendeditlabel.setText(_translate("Dialog", "发送区", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

